services:
  - type: web
    name: chatbot
    env: python
    pythonVersion: "3.10"
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: |
      PYTHONPATH=src gunicorn main:app --bind 0.0.0.0:$PORT
