services:
  - type: web
    name: chatBOt
    env: python
    pythonVersion: "3.10"
    buildCommand: "pip install --upgrade pip && pip install -r requirements.txt"
    startCommand: "gunicorn src.main:app"
    region: oregon
